# IPAM Subnet Allocation - On-demand child pool
# Creates VPC with subnet CIDRs allocated from an auto-created child pool
# No need to pre-create subnet pool in IPAM - Network creates it on-demand
#
# Prerequisites:
# - IPAM with VPC pool (e.g., globalPoolName: sandbox)
#
# What happens:
# 1. Network creates child pool under VPC's IPAM pool
# 2. Child pool allocates /24 CIDRs for subnets
# 3. Subnets get CIDRs from child pool
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Network
metadata:
  name: ondemand-subnets
  namespace: dev
spec:
  clusterName: my-cluster
  aws:
    config:
      region: us-east-1
  cidr:
    ipv4:
      ipam:
        globalPoolName: sandbox  # VPC CIDR from this pool
    mode: ipv4-only
  subnets:
    availabilityZones:
      - a
      - b
    netmaskLength: 24
    types:
      - public
      - private
    ipam:
      enabled: true  # No pool specified = creates child pool on-demand
  nat:
    enabled: false
